### ISSUE TITLE
pass env vars via /etc/environment

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/cloud-container#24]
To unify passing env vars for cloud-init and cloud container we should pass env vars from the /etc/environment file. By providing a `write-file` option to cloud init as per this post here

https://stackoverflow.com/questions/38044184/how-to-set-system-wide-environment-variable-in-cloud-config-file-on-digital-ocea

**Comment by AbdelrahmanElawady** [comment]
From the stackoverflow thread it seems to be OS dependent. `/etc/environment` seems to be working with Ubuntu but on Alpine for example it's in `/etc/profile`. Do we check what OS we are using or which env file exists and append based on that?

**Comment by muhamadazmy** [comment]
Yeah i know it's os dependent but was hoping that all distros uses the same file.
- We can't detect the os type of course, and we shouldn't rely on it
- If kernel+initramfs from cloud-container is used, there is no issue because we export the env to the init process
- We only need a standard cloud-init way to do it. Cloud-init then can do detection or whatever to pass env over. 
- Maybe check cloud-init docs for details on env otherwise we can't do it

**Comment by AbdelrahmanElawady** [comment]
After looking into it, it turned out there is no standard way or file that guarantee global environment variables for all processes to use. Cloud-init also does not handle environment variables at all. IMO I think the approaches we are doing now with setting it in containers and passing it as kernel args in VMs are enough.

**Comment by muhamadazmy** [comment]
I agree:
- There is no standard way to pass env vars to full VMs. There is no such thing also in cloud-init
- The way we do it works only with `container like` VMs where the VM has no kernel and we provide our own injected kernel+initramfs that can pass env vars to init.

I will close this as won't fix
