### ISSUE TITLE
Ping a remote ip after setting up the network interfaces to invalidate the gateway arp cache

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/cloud-container#9]
A delay occurs after deleting a vm and redeploying another with the same public ip until the public ip routes to the new machine. SSHing using ygg ip and pinging google for example makes it reachable instantly.

**Comment by AbdelrahmanElawady** [comment]
We do that [here](https://github.com/threefoldtech/cloud-container/blob/main/initcpio/hooks/bootstrap#L52) and we make sure routes used are the default gw associated with the public ip so it is no longer an issue.
